### ISSUE TITLE
Getting Unity Google Cardboard SDK Running.

### ISSUE THREAD

**Issue by ForeverTangent** [ForeverTangent/ArcadianDream#2]
Just trying to get Google Card Board Up.

**Comment by sirerr** [comment]
@ForeverTangent I think we're considering add controller input soon so I've added the OVR SDK from Oculus, we probably could remove the cardboard sdk but I'll leave that to you.

**Comment by ForeverTangent** [comment]
Hey Leonard,

Sorry for slow response.   Allergies on full attack.

Feel free to rip out or add anything you want to the code base.  The
Cardboard was just temporary thing to help me figure things out.

peace

Stan
